language: python
python: 
    - "2.6"
    - "2.7"
    - "3.0"
    - "3.1"
    - "3.2"
    - "3.3"
    - "3.4"
env:
    - DJANGO_VERSION=1.4
    - DJANGO_VERSION=1.5
    - DJANGO_VERSION=1.6


install: 
    - pip install -q Django==$DJANGO_VERSION
    - pip install -r requirements.txt

script: cd django_silky/ && ./manage.py test

