language: python
python: 
    - "2.7"
    - "3.4"
env:
    - DJANGO_VERSION=1.5
    - DJANGO_VERSION=1.6
    - DJANGO_VERSION=1.7

install:
    - pip install -q Django==$DJANGO_VERSION
    - pip install -r tests/test-requirements.txt

script: 
    - cp -r silk django_silky/silk
    - cd tests
    - python manage.py test
