language: python
python: 
    - "2.7"
    - "3.4"
    - "3.5"
env:
    - DJANGO="Django>=1.7.0,<1.8.0"
    - DJANGO="Django>=1.8.0,<1.9.0"
    - DJANGO="Django>=1.9.0,<1.10.0"
    - DJANGO="Django>=1.10a1,<1.11.0"

install:
    - pip install -q $DJANGO
    - pip install -r requirements.txt

script:
    - cd project
    - ./tests/test_migrations.sh
    - python manage.py test --noinput
    - cd -
